//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfComputadoras", Namespace="http://tempuri.org/", ItemName="computadoras")]
    [System.SerializableAttribute()]
    public class ArrayOfComputadoras : System.Collections.Generic.List<WEB.ServiceReference1.computadoras> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="computadoras", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class computadoras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long id_coField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titulo_coField;
        
        private System.Nullable<System.DateTime> fecha_coField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalle_coField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foto_coField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WEB.ServiceReference1.ArrayOfMantenimientos mantenimientosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id_co {
            get {
                return this.id_coField;
            }
            set {
                if ((this.id_coField.Equals(value) != true)) {
                    this.id_coField = value;
                    this.RaisePropertyChanged("id_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string titulo_co {
            get {
                return this.titulo_coField;
            }
            set {
                if ((object.ReferenceEquals(this.titulo_coField, value) != true)) {
                    this.titulo_coField = value;
                    this.RaisePropertyChanged("titulo_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> fecha_co {
            get {
                return this.fecha_coField;
            }
            set {
                if ((this.fecha_coField.Equals(value) != true)) {
                    this.fecha_coField = value;
                    this.RaisePropertyChanged("fecha_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string detalle_co {
            get {
                return this.detalle_coField;
            }
            set {
                if ((object.ReferenceEquals(this.detalle_coField, value) != true)) {
                    this.detalle_coField = value;
                    this.RaisePropertyChanged("detalle_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string foto_co {
            get {
                return this.foto_coField;
            }
            set {
                if ((object.ReferenceEquals(this.foto_coField, value) != true)) {
                    this.foto_coField = value;
                    this.RaisePropertyChanged("foto_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WEB.ServiceReference1.ArrayOfMantenimientos mantenimientos {
            get {
                return this.mantenimientosField;
            }
            set {
                if ((object.ReferenceEquals(this.mantenimientosField, value) != true)) {
                    this.mantenimientosField = value;
                    this.RaisePropertyChanged("mantenimientos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMantenimientos", Namespace="http://tempuri.org/", ItemName="mantenimientos")]
    [System.SerializableAttribute()]
    public class ArrayOfMantenimientos : System.Collections.Generic.List<WEB.ServiceReference1.mantenimientos> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mantenimientos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class mantenimientos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long id_maField;
        
        private long id_coField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fecha_maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detalle_maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reparacion_maField;
        
        private System.Nullable<bool> estado_maField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WEB.ServiceReference1.computadoras computadorasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id_ma {
            get {
                return this.id_maField;
            }
            set {
                if ((this.id_maField.Equals(value) != true)) {
                    this.id_maField = value;
                    this.RaisePropertyChanged("id_ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long id_co {
            get {
                return this.id_coField;
            }
            set {
                if ((this.id_coField.Equals(value) != true)) {
                    this.id_coField = value;
                    this.RaisePropertyChanged("id_co");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fecha_ma {
            get {
                return this.fecha_maField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_maField, value) != true)) {
                    this.fecha_maField = value;
                    this.RaisePropertyChanged("fecha_ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string detalle_ma {
            get {
                return this.detalle_maField;
            }
            set {
                if ((object.ReferenceEquals(this.detalle_maField, value) != true)) {
                    this.detalle_maField = value;
                    this.RaisePropertyChanged("detalle_ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reparacion_ma {
            get {
                return this.reparacion_maField;
            }
            set {
                if ((object.ReferenceEquals(this.reparacion_maField, value) != true)) {
                    this.reparacion_maField = value;
                    this.RaisePropertyChanged("reparacion_ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> estado_ma {
            get {
                return this.estado_maField;
            }
            set {
                if ((this.estado_maField.Equals(value) != true)) {
                    this.estado_maField = value;
                    this.RaisePropertyChanged("estado_ma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WEB.ServiceReference1.computadoras computadoras {
            get {
                return this.computadorasField;
            }
            set {
                if ((object.ReferenceEquals(this.computadorasField, value) != true)) {
                    this.computadorasField = value;
                    this.RaisePropertyChanged("computadoras");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.compusSoap")]
    public interface compusSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarCompusMantenimientosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarCompusMantenimientos", ReplyAction="*")]
        WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse SeleccionarCompusMantenimientos(WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarCompusMantenimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse> SeleccionarCompusMantenimientosAsync(WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarCompusMantenimientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarCompusMantenimientos", Namespace="http://tempuri.org/", Order=0)]
        public WEB.ServiceReference1.SeleccionarCompusMantenimientosRequestBody Body;
        
        public SeleccionarCompusMantenimientosRequest() {
        }
        
        public SeleccionarCompusMantenimientosRequest(WEB.ServiceReference1.SeleccionarCompusMantenimientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarCompusMantenimientosRequestBody {
        
        public SeleccionarCompusMantenimientosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarCompusMantenimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarCompusMantenimientosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WEB.ServiceReference1.SeleccionarCompusMantenimientosResponseBody Body;
        
        public SeleccionarCompusMantenimientosResponse() {
        }
        
        public SeleccionarCompusMantenimientosResponse(WEB.ServiceReference1.SeleccionarCompusMantenimientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarCompusMantenimientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WEB.ServiceReference1.ArrayOfComputadoras SeleccionarCompusMantenimientosResult;
        
        public SeleccionarCompusMantenimientosResponseBody() {
        }
        
        public SeleccionarCompusMantenimientosResponseBody(WEB.ServiceReference1.ArrayOfComputadoras SeleccionarCompusMantenimientosResult) {
            this.SeleccionarCompusMantenimientosResult = SeleccionarCompusMantenimientosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface compusSoapChannel : WEB.ServiceReference1.compusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class compusSoapClient : System.ServiceModel.ClientBase<WEB.ServiceReference1.compusSoap>, WEB.ServiceReference1.compusSoap {
        
        public compusSoapClient() {
        }
        
        public compusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public compusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public compusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public compusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse WEB.ServiceReference1.compusSoap.SeleccionarCompusMantenimientos(WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest request) {
            return base.Channel.SeleccionarCompusMantenimientos(request);
        }
        
        public WEB.ServiceReference1.ArrayOfComputadoras SeleccionarCompusMantenimientos() {
            WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest inValue = new WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest();
            inValue.Body = new WEB.ServiceReference1.SeleccionarCompusMantenimientosRequestBody();
            WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse retVal = ((WEB.ServiceReference1.compusSoap)(this)).SeleccionarCompusMantenimientos(inValue);
            return retVal.Body.SeleccionarCompusMantenimientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse> WEB.ServiceReference1.compusSoap.SeleccionarCompusMantenimientosAsync(WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest request) {
            return base.Channel.SeleccionarCompusMantenimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEB.ServiceReference1.SeleccionarCompusMantenimientosResponse> SeleccionarCompusMantenimientosAsync() {
            WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest inValue = new WEB.ServiceReference1.SeleccionarCompusMantenimientosRequest();
            inValue.Body = new WEB.ServiceReference1.SeleccionarCompusMantenimientosRequestBody();
            return ((WEB.ServiceReference1.compusSoap)(this)).SeleccionarCompusMantenimientosAsync(inValue);
        }
    }
}
