//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public long id_pe { get; set; }
        public string nombres_pe { get; set; }
        public string email_pe { get; set; }
        public string bio_pe { get; set; }
        public string web_pe { get; set; }
        public string foto_pe { get; set; }
        public string dni_pe { get; set; }
        public Nullable<System.DateTime> fecha_pe { get; set; }
    }
}
